from enum import Enum

class Municipality(str, Enum):
    CERDANYA = "CERDANYA"
    MARESME = "MARESME"
    BERGUEDA = "BERGUEDA"
    GENERAL = "GENERAL"
    UNKNOWN = "UNKNOWN"

class ContentCategory(str, Enum):
    AGENDA = "AGENDA"
    NOTICIES = "NOTICIES"
    ESPORTS = "ESPORTS"
    TURISME_ACTIU = "TURISME_ACTIU"
    NENS_I_JOVES = "NENS_I_JOVES"
    CULTURA = "CULTURA"
    GASTRONOMIA = "GASTRONOMIA"
    CONSELLS = "CONSELLS"
    ENTREVISTES = "ENTREVISTES"
    UNKNOWN = "UNKNOWN"

class ContentSubtype(str, Enum):
    NONE = "NONE"
    CULTURA_GENERAL = "CULTURA_GENERAL"
    CULTURA_BOOK = "CULTURA_BOOK"
    GASTRONOMIA_GENERAL = "GASTRONOMIA_GENERAL"
    GASTRONOMIA_RECIPE = "GASTRONOMIA_RECIPE"
    AGENDA_GENERAL = "AGENDA_GENERAL"
    AGENDA_WITH_ACTIVITIES = "AGENDA_WITH_ACTIVITIES"
    UNKNOWN = "UNKNOWN"

class ReviewReason(str, Enum):
    LOW_CLASSIFICATION_CONFIDENCE = "LOW_CLASSIFICATION_CONFIDENCE"
    LOW_EXTRACTION_CONFIDENCE = "LOW_EXTRACTION_CONFIDENCE"
    MISSING_FEATURED_IMAGE = "MISSING_FEATURED_IMAGE"
    MISSING_REQUIRED_DATE = "MISSING_REQUIRED_DATE"
    AMBIGUOUS_CATEGORY = "AMBIGUOUS_CATEGORY"
    AMBIGUOUS_MUNICIPALITY = "AMBIGUOUS_MUNICIPALITY"
    WEAK_GROUPING = "WEAK_GROUPING"
    MISSING_REQUIRED_FIELDS = "MISSING_REQUIRED_FIELDS"
    VALIDATION_FAILED = "VALIDATION_FAILED"
    EXPORT_FAILED = "EXPORT_FAILED"
    CONFLICTING_SIGNALS = "CONFLICTING_SIGNALS"
    INSUFFICIENT_TEXT = "INSUFFICIENT_TEXT"

class ExtractionMethod(str, Enum):
    NATIVE_PDF = "NATIVE_PDF"
    DOCX_PARSER = "DOCX_PARSER"
    OCR_PDF = "OCR_PDF"
    OCR_IMAGE = "OCR_IMAGE"
    UNKNOWN = "UNKNOWN"

class ExportFormat(str, Enum):
    JSON_WP_IMPORT = "JSON_WP_IMPORT"
    REST_API_DIRECT = "REST_API_DIRECT"

class ImageRole(str, Enum):
    FEATURED = "FEATURED"
    INLINE = "INLINE"
    GALLERY = "GALLERY"
    BLOCK_CONTEXTUAL = "BLOCK_CONTEXTUAL"
    UNKNOWN = "UNKNOWN"

class ConfidenceBand(str, Enum):
    HIGH = "HIGH"
    MEDIUM = "MEDIUM"
    LOW = "LOW"
    UNKNOWN = "UNKNOWN"

class ValidationSeverity(str, Enum):
    INFO = "INFO"
    WARNING = "WARNING"
    ERROR = "ERROR"
    CRITICAL = "CRITICAL"

class SourceFileRole(str, Enum):
    PRIMARY_DOCUMENT = "PRIMARY_DOCUMENT"
    SUPPORTING_DOCUMENT = "SUPPORTING_DOCUMENT"
    PRIMARY_IMAGE = "PRIMARY_IMAGE"
    SUPPORTING_IMAGE = "SUPPORTING_IMAGE"
    UNKNOWN = "UNKNOWN"

class CandidateGroupingStrategy(str, Enum):
    SINGLE_FILE = "SINGLE_FILE"
    DIRECTORY_BASED = "DIRECTORY_BASED"
    NAME_PROXIMITY = "NAME_PROXIMITY"
    MIXED_INFERENCE = "MIXED_INFERENCE"
    UNKNOWN = "UNKNOWN"

class EventLevel(str, Enum):
    INFO = "INFO"
    WARNING = "WARNING"
    ERROR = "ERROR"
    CRITICAL = "CRITICAL"

class ReprocessingScope(str, Enum):
    EXTRACTION = "EXTRACTION"
    CLASSIFICATION = "CLASSIFICATION"
    EDITORIAL = "EDITORIAL"
    EXPORT = "EXPORT"
    FULL_REBUILD = "FULL_REBUILD"
